spring:
  data:
    mongodb:
      host: prod3.sjes.sanjiang.info
      port: 27017
      database: sjes-hub-api



eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://prod1.sjes.sanjiang.info:8761/eureka/